// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2_Infraestructura;

#nullable disable

namespace _2_Infraestructura.Migrations
{
    [DbContext(typeof(ProyectosContext))]
    [Migration("20250526122954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_4_Dominio.ApprovalRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("AreaId");

                    b.HasIndex("TypeId");

                    b.ToTable("ApprovalRule", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApproverRoleId = 1,
                            MaxAmount = 100000m,
                            MinAmount = 0m,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2L,
                            ApproverRoleId = 2,
                            MaxAmount = 20000m,
                            MinAmount = 5000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3L,
                            ApproverRoleId = 2,
                            AreaId = 2,
                            MaxAmount = 20000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4L,
                            ApproverRoleId = 3,
                            MaxAmount = 0m,
                            MinAmount = 20000m,
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 5L,
                            ApproverRoleId = 2,
                            AreaId = 1,
                            MaxAmount = 0m,
                            MinAmount = 5000m,
                            StepOrder = 2,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 6L,
                            ApproverRoleId = 1,
                            MaxAmount = 10000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 7L,
                            ApproverRoleId = 4,
                            AreaId = 2,
                            MaxAmount = 10000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 8L,
                            ApproverRoleId = 2,
                            AreaId = 2,
                            MaxAmount = 30000m,
                            MinAmount = 10000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 9L,
                            ApproverRoleId = 3,
                            AreaId = 3,
                            MaxAmount = 0m,
                            MinAmount = 30000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 10L,
                            ApproverRoleId = 4,
                            MaxAmount = 50000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("_4_Dominio.ApprovalStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("ApprovalStatus", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            id = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            id = 4,
                            Name = "Observed"
                        });
                });

            modelBuilder.Entity("_4_Dominio.ApproverRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("ApproverRole", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Líder de Área"
                        },
                        new
                        {
                            id = 2,
                            Name = "Gerente"
                        },
                        new
                        {
                            id = 3,
                            Name = "Director"
                        },
                        new
                        {
                            id = 4,
                            Name = "Comité Tecnico"
                        });
                });

            modelBuilder.Entity("_4_Dominio.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("Area", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Finanzas"
                        },
                        new
                        {
                            id = 2,
                            Name = "Tecnología"
                        },
                        new
                        {
                            id = 3,
                            Name = "Recursos Humanos"
                        },
                        new
                        {
                            id = 4,
                            Name = "Operaciones"
                        });
                });

            modelBuilder.Entity("_4_Dominio.ProjectApprovalStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("ProjectProposalId");

                    b.HasIndex("StatusId");

                    b.ToTable("ProjectApprovalStep", (string)null);
                });

            modelBuilder.Entity("_4_Dominio.ProjectProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("ProjectProposal", (string)null);
                });

            modelBuilder.Entity("_4_Dominio.ProjectType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("ProjectType", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Mejora de Procesos"
                        },
                        new
                        {
                            id = 2,
                            Name = "Innovación y Desarrollo"
                        },
                        new
                        {
                            id = 3,
                            Name = "Infraestructura"
                        },
                        new
                        {
                            id = 4,
                            Name = "Capacitación Interna"
                        });
                });

            modelBuilder.Entity("_4_Dominio.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Email = "jferreyra@unaj.com",
                            Name = "José Ferreyra",
                            RoleId = 2
                        },
                        new
                        {
                            id = 2,
                            Email = "alucero@unaj.com",
                            Name = "Ana Lucero",
                            RoleId = 1
                        },
                        new
                        {
                            id = 3,
                            Email = "gmolinas@unaj.com",
                            Name = "Gonzalo Molinas",
                            RoleId = 2
                        },
                        new
                        {
                            id = 4,
                            Email = "lolivera@unaj.com",
                            Name = "Lucas Olivera",
                            RoleId = 3
                        },
                        new
                        {
                            id = 5,
                            Email = "dfagundez@unaj.com",
                            Name = "Danilo Fagundez",
                            RoleId = 4
                        },
                        new
                        {
                            id = 6,
                            Email = "ggalli@unaj.com",
                            Name = "Gabriel Galli",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("_4_Dominio.ApprovalRule", b =>
                {
                    b.HasOne("_4_Dominio.ApproverRole", "ApproverRole")
                        .WithMany()
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4_Dominio.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("_4_Dominio.ProjectType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("ApproverRole");

                    b.Navigation("Area");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("_4_Dominio.ProjectApprovalStep", b =>
                {
                    b.HasOne("_4_Dominio.ApproverRole", "ApproverRole")
                        .WithMany()
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_4_Dominio.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_4_Dominio.ProjectProposal", "ProjectProposal")
                        .WithMany()
                        .HasForeignKey("ProjectProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_4_Dominio.ApprovalStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApproverRole");

                    b.Navigation("ApproverUser");

                    b.Navigation("ProjectProposal");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("_4_Dominio.ProjectProposal", b =>
                {
                    b.HasOne("_4_Dominio.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4_Dominio.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4_Dominio.ApprovalStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4_Dominio.ProjectType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("CreatedBy");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("_4_Dominio.User", b =>
                {
                    b.HasOne("_4_Dominio.ApproverRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
